create table
  public.sign_up (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    email character varying not null default ''::character varying,
    page character varying not null default ''::character varying,
    constraint sign_up_pkey primary key (id)
  ) tablespace pg_default;